---
- name: Act on Insights events
  hosts: localhost

  sources:
    - redhatinsights.eda.insights:
        host: 0.0.0.0
        port: 5000
        token: redhatinsighttoken

  rules:
    - name: Execute say-hello.yml playbook
      condition: event.payload is defined
      actions:
        - debug:
        - run_job_template:
            name: EDA - Hello
            organization: Default
