---
- name: Prometheus Alertmanager
  hosts: localhost
  sources:
    - ansible.eda.alertmanager:
        host: 0.0.0.0
        port: 6999
  rules:
    - name: Reprovision Webserver if Alert from Prometheus
      condition:
        all:
          - event.alert.status == "firing"
          - event.alert.labels.alertname == "WebsiteDown"
      actions:
        - run_job_template:
            name: Connection Check
            organization: eu.aut.AADSMeetfnd4tpslinuxserverMem.us
